### PR TITLE
Inclusion of JavaScript Message Event, Navigation Decision and Update of Dependencies

### PR DESCRIPTION
**Pull request by ronymesquita**
### Changes

* Updated dependencies in `pubspec.yaml`
* Changed `impl.dart` to use the new version of `flutter_markdown`
* Removed `cupertino_icons`
* Changed `.gitignore`
* Added `analysis_options.yaml` to ignore undefined_prefixed_name warning

The tests was made with the code in the example folder, using Flutter 1.22.2 (stable) and 1.23.0-18-1.pre (beta).

### CODE REVIEW

**Comment by rodydavis** [comment]
Can you resolve the conflicts? Ill merge and deploy

**Comment by ronymesquita** [comment]
Done.

:+1:

**Comment by ronymesquita** [comment]
The key idea is to add the equivalent of `javascriptChannels` and `navigationDelegate` of [webview_flutter](https://pub.dev/packages/webview_flutter) to this package.

**Changes**:
* Added JavaScript window message events
* Added navigation decision
* Update of Android and Gradle versions to the example project

**Notes**:
* The example project now has [Summernote](https://summernote.org), leveraging the use of JavaScript [MessageEvent](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent)
* The `navigationDelegate` property can be used to block the navigation
* If nothing more needs to be changed, the `webNavigationDelegate` property can be used with the package [oauth2](https://pub.dev/packages/oauth2) to use Authorization Code Grant. I have not tested it yet.

> ### Summernote example

Flutter with Summernote

**Comment by ronymesquita** [comment]
Hello, @rodydavis.

I am very glad to be able to add new properties.
Please, can you review the pull request?

**Comment by rodydavis** [comment]
LGTM

**Pull request merged**
